server:
  address: 127.0.0.1
  port: 8999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /learn_mybatis_plus

spring:
  application:
    name: learn-mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.253:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl