server:
  address: 127.0.0.1
  port: 8999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /learn_boot

spring:
  application:
    name: learn-boot
  profiles:
    active: @profilesActive@

custom:
  name: application.yml自定义用户
  # 自定义上传文件的本地真实路径
  upload-path: E:\jungle\github\zz-guide\springboot-guide\learn-boot\src\main\resources\upload