spring:
  application:
    name: demo1
  profiles:
    active: @profiles.active@
server:
  port: 8999

logging:
  file:
    path: logs
    name: log.log
  pattern:
     file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    org:
      zz: debug