server:
  address: 127.0.0.1
  port: 8999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /learn_satoken

spring:
  application:
    name: learn-satoken
  datasource:
    url: jdbc:mysql://192.168.200.253:3306/test
    username: root
    password: root

# springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'user'
#      paths-to-match: '/**'
#      packages-to-scan: org.zz.demo3.controller
#
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn